### ISSUE TITLE
soketto-0.3.1->error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature

### ISSUE THREAD

**Issue by bitxx** [twittner/twist#17]
When I build the latest Substrate code，it is use soketto-0.3.1 and show like this：
<img width="889" alt="截屏2020-01-1103 28 45" src="https://user-images.githubusercontent.com/13200618/72180906-2c4d8900-3423-11ea-8be9-64adaed37ebb.png">

**Comment by niklasad1** [comment]
@jason-wj 

Update your `rust toolchain` to `1.40.0` and it will compile

**Comment by dp289m** [comment]
Got it. Thanks. It worked.

**Comment by Hai-Hoang-88** [comment]
@niklasad1 Hello, I have faced the same problem when I install auto autopy. 
the errors said:
` error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
       --> C:\Users\PC3\.cargo\registry\src\github.com-1ecc6299db9ec823\memchr-2.4.0\src\memmem\prefilter\mod.rs:152:1
        |
    152 | #[non_exhaustive]
        | ^^^^^^^^^^^^^^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/44109
        = help: add `#![feature(non_exhaustive)]` to the crate attributes to enable`

even I have rust:
`   stable-x86_64-pc-windows-msvc unchanged - rustc 1.53.0 (53cb7b09b 2021-06-17)
  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.56.0-nightly (b70888601 2021-07-28)`

Can you help me, thank you so much

**Comment by niklasad1** [comment]
hmm, sounds weird that shouldn't happen on a toolchain where the version is `>= 1.40` 

Are you sure that you haven't unintentionally [overwritten your toolchain](https://rust-lang.github.io/rustup/overrides.html)?

**Comment by Hai-Hoang-88** [comment]
This is one I have when run `rustup show`:

`C:\Users\PC3>rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\PC3\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2019-10-05-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

nightly-2019-10-05-x86_64-pc-windows-msvc (default)
rustc 1.40.0-nightly (2e7244807 2019-10-04)`

**Comment by niklasad1** [comment]
Yeah, it was like I thought you have enabled an `old nightly version` that causes this please have a look have how https://rust-lang.github.io/rustup/overrides.html how overrides work in Rust.

`$ cargo +stable --build` will probably work for you

The best way would be to uninstall the old nightly version and enable `nightly-x86_64-pc-windows-msvc` as default ^^
