### ISSUE TITLE
ReservedOpCode error

### ISSUE THREAD

**Issue by sander2** [twittner/twist#26]
While using jsonrpsee we see the `Ws(Codec(ReservedOpCode))` error occurring. Currently we use a modified version of jsonrpsees master branch, which exits the application on `inner` errors, which includes the aforementioned error. Unfortunately it's not easy in jsonrpsee to match only the disconnects, due to the code being generic over errors. Would it make sense at all for us to continue communication when we get a `ReservedOpCode`? I think we will have missed a message for sure, but other than that, would the library recover if we ignore the error?

**Comment by niklasad1** [comment]
I think this is related to that the `jsonrpsee ws client` is incorrectly designed w.r.t [soketto Receiver is not cancel-safe](https://github.com/paritytech/soketto/issues/25#issuecomment-723498084), thus if you could check to logs if something else weird happens before the `ReserverdOpCode` that would be good and seems likely IMHO.

**Comment by dvdplm** [comment]
@sander2 is this still relevant with the latest version of `jsonrpsee`?

**Comment by dvdplm** [comment]
Closing as stale.
