### ISSUE TITLE
Is `rustfmt` welcome here?

### ISSUE THREAD

**Issue by dvdplm** [twittner/twist#28]
Currently the code base does not use `rustfmt`. As this is a somewhat contentious topic I thought I'd ask before opening a PR to enforce it.

**Comment by maciejhirsz** [comment]
I'm happy to embrace fmt here. Most code is pretty standard style, and having run `cargo fmt` on the code not that much is changed, mostly missing tailing commas and chain method calls being split into multiple lines.

**Comment by dvdplm** [comment]
Let's do it.

/cc @tomaka

**Comment by tomaka** [comment]
I'm :+1: for rustfmt everywhere.
