### ISSUE TITLE
Update futures-preview crate to "0.3.0-alpha.19"

### ISSUE THREAD

**Issue by serzhiio** [twittner/twist#4]
subj

**Comment by twittner** [comment]
What do you mean? The `develop` branch depends on `^0.3.0-alpha.18`.

**Comment by serzhiio** [comment]
Ohh... i'm very sorry. Havent noticed `^` sign.

**Comment by twittner** [comment]
It is not there, but [implied](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html):

> The string "0.1.12" is a semver version requirement. Since this string does not have any operators in it, it is interpreted the same way as if we had specified "^0.1.12", which is called a caret requirement.
