### ISSUE TITLE
Custom headers on client

### ISSUE THREAD

**Issue by 717a56e1** [twittner/twist#46]
Any interest on adding this feature? I need this for `jsonrpsee`, so I have a sketch written around `http::HeaderMap` instead of the singleton `origin: Option<&'a str>`.

**Comment by maciejhirsz** [comment]
Sure, we could take `&[httparse::Header]` instead (we already use `httparse`, and it might be a good first step to also expose those on server responses).

**Comment by 717a56e1** [comment]
Sure, will get a PR up. Will convert `http::HeaderMap` to `&[httparse::Header]`.

**Comment by 717a56e1** [comment]
Got it done on the client side, tested with some changes to jsonrpcsee as well #47

**Comment by jsdw** [comment]
It looks like this is resolved now so I'll close this :) Please re-open if I'm mistaken!
